/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import sv.gob.mh.oim.pojo.ChildTableAccount;
import io.swagger.model.Resource;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class Account   {
  @JsonProperty("userLogin")
  private String userLogin = null;

  @JsonProperty("userKey")
  private String userKey = null;

  @JsonProperty("accountKey")
  private String accountKey = null;

  @JsonProperty("userCustomLogin")
  private String userCustomLogin = null;

  @JsonProperty("applicationName")
  private String applicationName = null;

  @JsonProperty("applicationKeyName")
  private String applicationKeyName = null;

  @JsonProperty("childsTables")
  private List<ChildTableAccount> childsTables = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("resource")
  private Resource resource = null;

  @JsonProperty("justification")
  private String justification = null;

  @JsonProperty("accountId")
  private String accountId = null;

  public Account userLogin(String userLogin) {
    this.userLogin = userLogin;
    return this;
  }

  /**
   * 
   * @return userLogin
   **/
  @JsonProperty("userLogin")
  @ApiModelProperty(value = "")
  public String getUserLogin() {
    return userLogin;
  }

  public void setUserLogin(String userLogin) {
    this.userLogin = userLogin;
  }

  public Account userKey(String userKey) {
    this.userKey = userKey;
    return this;
  }

  /**
   * 
   * @return userKey
   **/
  @JsonProperty("userKey")
  @ApiModelProperty(value = "")
  public String getUserKey() {
    return userKey;
  }

  public void setUserKey(String userKey) {
    this.userKey = userKey;
  }

  public Account accountKey(String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

  /**
   * 
   * @return accountKey
   **/
  @JsonProperty("accountKey")
  @ApiModelProperty(value = "")
  public String getAccountKey() {
    return accountKey;
  }

  public void setAccountKey(String accountKey) {
    this.accountKey = accountKey;
  }

  public Account userCustomLogin(String userCustomLogin) {
    this.userCustomLogin = userCustomLogin;
    return this;
  }

  /**
   * 
   * @return userCustomLogin
   **/
  @JsonProperty("userCustomLogin")
  @ApiModelProperty(value = "")
  public String getUserCustomLogin() {
    return userCustomLogin;
  }

  public void setUserCustomLogin(String userCustomLogin) {
    this.userCustomLogin = userCustomLogin;
  }

  public Account applicationName(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

  /**
   * 
   * @return applicationName
   **/
  @JsonProperty("applicationName")
  @ApiModelProperty(value = "")
  public String getApplicationName() {
    return applicationName;
  }

  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }

  public Account applicationKeyName(String applicationKeyName) {
    this.applicationKeyName = applicationKeyName;
    return this;
  }

  /**
   * 
   * @return applicationKeyName
   **/
  @JsonProperty("applicationKeyName")
  @ApiModelProperty(value = "")
  public String getApplicationKeyName() {
    return applicationKeyName;
  }

  public void setApplicationKeyName(String applicationKeyName) {
    this.applicationKeyName = applicationKeyName;
  }

  public Account childsTables(List<ChildTableAccount> childsTables) {
    this.childsTables = childsTables;
    return this;
  }

  public Account addChildsTablesItem(ChildTableAccount childsTablesItem) {
    if (this.childsTables == null) {
      this.childsTables = new ArrayList<ChildTableAccount>();
    }
    this.childsTables.add(childsTablesItem);
    return this;
  }

  /**
   * 
   * @return childsTables
   **/
  @JsonProperty("childsTables")
  @ApiModelProperty(value = "")
  @Valid
  public List<ChildTableAccount> getChildsTables() {
    return childsTables;
  }

  public void setChildsTables(List<ChildTableAccount> childsTables) {
    this.childsTables = childsTables;
  }

  public Account status(String status) {
    this.status = status;
    return this;
  }

  /**
   * 
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Account resource(Resource resource) {
    this.resource = resource;
    return this;
  }

  /**
   * 
   * @return resource
   **/
  @JsonProperty("resource")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  @Valid
  public Resource getResource() {
    return resource;
  }

  public void setResource(Resource resource) {
    this.resource = resource;
  }

  public Account justification(String justification) {
    this.justification = justification;
    return this;
  }

  /**
   * 
   * @return justification
   **/
  @JsonProperty("justification")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getJustification() {
    return justification;
  }

  public void setJustification(String justification) {
    this.justification = justification;
  }

  public Account accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * 
   * @return accountId
   **/
  @JsonProperty("accountId")
  @ApiModelProperty(value = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.userLogin, account.userLogin) &&
        Objects.equals(this.userKey, account.userKey) &&
        Objects.equals(this.accountKey, account.accountKey) &&
        Objects.equals(this.userCustomLogin, account.userCustomLogin) &&
        Objects.equals(this.applicationName, account.applicationName) &&
        Objects.equals(this.applicationKeyName, account.applicationKeyName) &&
        Objects.equals(this.childsTables, account.childsTables) &&
        Objects.equals(this.status, account.status) &&
        Objects.equals(this.resource, account.resource) &&
        Objects.equals(this.justification, account.justification) &&
        Objects.equals(this.accountId, account.accountId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userLogin, userKey, accountKey, userCustomLogin, applicationName, applicationKeyName, childsTables, status, resource, justification, accountId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    userLogin: ").append(toIndentedString(userLogin)).append("\n");
    sb.append("    userKey: ").append(toIndentedString(userKey)).append("\n");
    sb.append("    accountKey: ").append(toIndentedString(accountKey)).append("\n");
    sb.append("    userCustomLogin: ").append(toIndentedString(userCustomLogin)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    applicationKeyName: ").append(toIndentedString(applicationKeyName)).append("\n");
    sb.append("    childsTables: ").append(toIndentedString(childsTables)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    justification: ").append(toIndentedString(justification)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

