/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class AttributeAccount   {
  @JsonProperty("key")
  private String key = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("tableKey")
  private String tableKey = null;

  @JsonProperty("status")
  private String status = null;

  public AttributeAccount key(String key) {
    this.key = key;
    return this;
  }

   public AttributeAccount() {
    }
  
  
   public AttributeAccount(String key,String value) {
       this.key=key;
       this.value=value;
   }
  

  /**
   * 
   * @return key
   **/
  @JsonProperty("key")
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public AttributeAccount value(String value) {
    this.value = value;
    return this;
  }

  /**
   * 
   * @return value
   **/
  @JsonProperty("value")
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public AttributeAccount tableKey(String tableKey) {
    this.tableKey = tableKey;
    return this;
  }

  /**
   * 
   * @return tableKey
   **/
  @JsonProperty("tableKey")
  @ApiModelProperty(value = "")
  public String getTableKey() {
    return tableKey;
  }

  public void setTableKey(String tableKey) {
    this.tableKey = tableKey;
  }

  public AttributeAccount status(String status) {
    this.status = status;
    return this;
  }

  /**
   * 
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributeAccount attributeAccount = (AttributeAccount) o;
    return Objects.equals(this.key, attributeAccount.key) &&
        Objects.equals(this.value, attributeAccount.value) &&
        Objects.equals(this.tableKey, attributeAccount.tableKey) &&
        Objects.equals(this.status, attributeAccount.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, value, tableKey, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributeAccount {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    tableKey: ").append(toIndentedString(tableKey)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

