/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class Audit   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("user")
  private String user = null;

  @JsonProperty("requester")
  private String requester = null;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("justification")
  private String justification = null;

  public Audit id(String id) {
    this.id = id;
    return this;
  }

  /**
   * 
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Audit user(String user) {
    this.user = user;
    return this;
  }

  /**
   * 
   * @return user
   **/
  @JsonProperty("user")
  @ApiModelProperty(value = "")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }

  public Audit requester(String requester) {
    this.requester = requester;
    return this;
  }

  /**
   * 
   * @return requester
   **/
  @JsonProperty("requester")
  @ApiModelProperty(value = "")
  public String getRequester() {
    return requester;
  }

  public void setRequester(String requester) {
    this.requester = requester;
  }

  public Audit date(String date) {
    this.date = date;
    return this;
  }

  /**
   * 
   * @return date
   **/
  @JsonProperty("date")
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Audit justification(String justification) {
    this.justification = justification;
    return this;
  }

  /**
   * 
   * @return justification
   **/
  @JsonProperty("justification")
  @ApiModelProperty(value = "")
  public String getJustification() {
    return justification;
  }

  public void setJustification(String justification) {
    this.justification = justification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Audit audit = (Audit) o;
    return Objects.equals(this.id, audit.id) &&
        Objects.equals(this.user, audit.user) &&
        Objects.equals(this.requester, audit.requester) &&
        Objects.equals(this.date, audit.date) &&
        Objects.equals(this.justification, audit.justification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, user, requester, date, justification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Audit {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    requester: ").append(toIndentedString(requester)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    justification: ").append(toIndentedString(justification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

