/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class ChildTableAccount   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("alias")
  private String alias = null;

  @JsonProperty("tableName")
  private String tableName = null;

  @JsonProperty("attributes")
  private List<AttributeAccount> attributes = null;

  public ChildTableAccount id(String id) {
    this.id = id;
    return this;
  }

  /**
   * 
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ChildTableAccount name(String name) {
    this.name = name;
    return this;
  }

  /**
   * 
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ChildTableAccount alias(String alias) {
    this.alias = alias;
    return this;
  }

  /**
   * 
   * @return alias
   **/
  @JsonProperty("alias")
  @ApiModelProperty(value = "")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public ChildTableAccount tableName(String tableName) {
    this.tableName = tableName;
    return this;
  }

  /**
   * 
   * @return tableName
   **/
  @JsonProperty("tableName")
  @ApiModelProperty(value = "")
  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }

  public ChildTableAccount attributes(List<AttributeAccount> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ChildTableAccount addAttributesItem(AttributeAccount attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<AttributeAccount>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

  /**
   * 
   * @return attributes
   **/
  @JsonProperty("attributes")
  @ApiModelProperty(value = "")
  @Valid
  public List<AttributeAccount> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<AttributeAccount> attributes) {
    this.attributes = attributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChildTableAccount childTableAccount = (ChildTableAccount) o;
    return Objects.equals(this.id, childTableAccount.id) &&
        Objects.equals(this.name, childTableAccount.name) &&
        Objects.equals(this.alias, childTableAccount.alias) &&
        Objects.equals(this.tableName, childTableAccount.tableName) &&
        Objects.equals(this.attributes, childTableAccount.attributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, alias, tableName, attributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChildTableAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

