/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Entitlement
 */
@ApiModel(description = "Entitlement")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class Entitlement   {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("accountKey")
  private String accountKey = null;

  @JsonProperty("accountName")
  private String accountName = null;

  @JsonProperty("userLogin")
  private String userLogin = null;

  @JsonProperty("userKey")
  private String userKey = null;

  @JsonProperty("entitlementId")
  private String entitlementId = null;

  @JsonProperty("entitlementInstanceId")
  private String entitlementInstanceId = null;

  @JsonProperty("endDate")
  private String endDate = null;

  @JsonProperty("justification")
  private String justification = null;

  public Entitlement name(String name) {
    this.name = name;
    return this;
  }

  /**
   * 
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Entitlement status(String status) {
    this.status = status;
    return this;
  }

  /**
   * 
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Entitlement accountKey(String accountKey) {
    this.accountKey = accountKey;
    return this;
  }

  /**
   * 
   * @return accountKey
   **/
  @JsonProperty("accountKey")
  @ApiModelProperty(value = "")
  public String getAccountKey() {
    return accountKey;
  }

  public void setAccountKey(String accountKey) {
    this.accountKey = accountKey;
  }

  public Entitlement accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

  /**
   * 
   * @return accountName
   **/
  @JsonProperty("accountName")
  @ApiModelProperty(value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public Entitlement userLogin(String userLogin) {
    this.userLogin = userLogin;
    return this;
  }

  /**
   * 
   * @return userLogin
   **/
  @JsonProperty("userLogin")
  @ApiModelProperty(value = "")
  public String getUserLogin() {
    return userLogin;
  }

  public void setUserLogin(String userLogin) {
    this.userLogin = userLogin;
  }

  public Entitlement userKey(String userKey) {
    this.userKey = userKey;
    return this;
  }

  /**
   * 
   * @return userKey
   **/
  @JsonProperty("userKey")
  @ApiModelProperty(value = "")
  public String getUserKey() {
    return userKey;
  }

  public void setUserKey(String userKey) {
    this.userKey = userKey;
  }

  public Entitlement entitlementId(String entitlementId) {
    this.entitlementId = entitlementId;
    return this;
  }

  /**
   * 
   * @return entitlementId
   **/
  @JsonProperty("entitlementId")
  @ApiModelProperty(value = "")
  public String getEntitlementId() {
    return entitlementId;
  }

  public void setEntitlementId(String entitlementId) {
    this.entitlementId = entitlementId;
  }

  public Entitlement entitlementInstanceId(String entitlementInstanceId) {
    this.entitlementInstanceId = entitlementInstanceId;
    return this;
  }

  /**
   * 
   * @return entitlementInstanceId
   **/
  @JsonProperty("entitlementInstanceId")
  @ApiModelProperty(value = "")
  public String getEntitlementInstanceId() {
    return entitlementInstanceId;
  }

  public void setEntitlementInstanceId(String entitlementInstanceId) {
    this.entitlementInstanceId = entitlementInstanceId;
  }

  public Entitlement endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * 
   * @return endDate
   **/
  @JsonProperty("endDate")
  @ApiModelProperty(value = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public Entitlement justification(String justification) {
    this.justification = justification;
    return this;
  }

  /**
   * 
   * @return justification
   **/
  @JsonProperty("justification")
  @ApiModelProperty(value = "")
  public String getJustification() {
    return justification;
  }

  public void setJustification(String justification) {
    this.justification = justification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entitlement entitlement = (Entitlement) o;
    return Objects.equals(this.name, entitlement.name) &&
        Objects.equals(this.status, entitlement.status) &&
        Objects.equals(this.accountKey, entitlement.accountKey) &&
        Objects.equals(this.accountName, entitlement.accountName) &&
        Objects.equals(this.userLogin, entitlement.userLogin) &&
        Objects.equals(this.userKey, entitlement.userKey) &&
        Objects.equals(this.entitlementId, entitlement.entitlementId) &&
        Objects.equals(this.entitlementInstanceId, entitlement.entitlementInstanceId) &&
        Objects.equals(this.endDate, entitlement.endDate) &&
        Objects.equals(this.justification, entitlement.justification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, accountKey, accountName, userLogin, userKey, entitlementId, entitlementInstanceId, endDate, justification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entitlement {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    accountKey: ").append(toIndentedString(accountKey)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    userLogin: ").append(toIndentedString(userLogin)).append("\n");
    sb.append("    userKey: ").append(toIndentedString(userKey)).append("\n");
    sb.append("    entitlementId: ").append(toIndentedString(entitlementId)).append("\n");
    sb.append("    entitlementInstanceId: ").append(toIndentedString(entitlementInstanceId)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    justification: ").append(toIndentedString(justification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

