/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class Identity   {
  @JsonProperty("userLogin")
  private String userLogin = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("commonName")
  private String commonName = null;

  @JsonProperty("homePhone")
  private String homePhone = null;

  @JsonProperty("organizationName")
  private String organizationName = null;

  @JsonProperty("mobile")
  private String mobile = null;

  @JsonProperty("startDate")
  private String startDate = null;

  @JsonProperty("changePassword")
  private Boolean changePassword = null;

  @JsonProperty("cargo")
  private String cargo = null;

  @JsonProperty("institucion")
  private String institucion = null;

  @JsonProperty("dependencia")
  private String dependencia = null;

  @JsonProperty("nivel1")
  private String nivel1 = null;

  @JsonProperty("nivel2")
  private String nivel2 = null;

  @JsonProperty("nivel3")
  private String nivel3 = null;

  @JsonProperty("nivel4")
  private String nivel4 = null;

  @JsonProperty("correoAlternativo")
  private String correoAlternativo = null;

  @JsonProperty("nit")
  private String nit = null;
  
  @JsonProperty("dui")
  private String dui = null;

  @JsonProperty("extension")
  private String extension = null;

  @JsonProperty("tipoUsuario")
  private String tipoUsuario = null;

  @JsonProperty("comentarios")
  private String comentarios = null;

  @JsonProperty("creadoPor")
  private String creadoPor = null;

  @JsonProperty("actualizadoPor")
  private String actualizadoPor = null;

  @JsonProperty("creadoEn")
  private String creadoEn = null;

  @JsonProperty("actualizadoEn")
  private String actualizadoEn = null;

  @JsonProperty("justification")
  private String justification = null;

  @JsonProperty("estado")
  private String estado = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("password")
  private String password = null;
  
  @JsonProperty("perfilUsuario")
  private String perfilUsuario = null;
  
  @JsonProperty("endDate")
  private String endDate = null;

    public String getPerfilUsuario() {
        return perfilUsuario;
    }

    public void setPerfilUsuario(String perfilUsuario) {
        this.perfilUsuario = perfilUsuario;
    }
  
  

  public Identity userLogin(String userLogin) {
    this.userLogin = userLogin;
    return this;
  }

  /**
   * 
   * @return userLogin
   **/
  @JsonProperty("userLogin")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getUserLogin() {
    return userLogin;
  }

  public void setUserLogin(String userLogin) {
    this.userLogin = userLogin;
  }

  public Identity email(String email) {
    this.email = email;
    return this;
  }

  /**
   * 
   * @return email
   **/
  @JsonProperty("email")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Identity firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * 
   * @return firstName
   **/
  @JsonProperty("firstName")
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Identity lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * 
   * @return lastName
   **/
  @JsonProperty("lastName")
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Identity commonName(String commonName) {
    this.commonName = commonName;
    return this;
  }

  /**
   * 
   * @return commonName
   **/
  @JsonProperty("commonName")
  @ApiModelProperty(value = "")
  public String getCommonName() {
    return commonName;
  }

  public void setCommonName(String commonName) {
    this.commonName = commonName;
  }

  public Identity homePhone(String homePhone) {
    this.homePhone = homePhone;
    return this;
  }

  /**
   * 
   * @return homePhone
   **/
  @JsonProperty("homePhone")
  @ApiModelProperty(value = "")
  public String getHomePhone() {
    return homePhone;
  }

  public void setHomePhone(String homePhone) {
    this.homePhone = homePhone;
  }

  public Identity organizationName(String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  /**
   * 
   * @return organizationName
   **/
  @JsonProperty("organizationName")
  @ApiModelProperty(value = "")
  public String getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(String organizationName) {
    this.organizationName = organizationName;
  }

  public Identity mobile(String mobile) {
    this.mobile = mobile;
    return this;
  }

  /**
   * 
   * @return mobile
   **/
  @JsonProperty("mobile")
  @ApiModelProperty(value = "")
  public String getMobile() {
    return mobile;
  }

  public void setMobile(String mobile) {
    this.mobile = mobile;
  }

  public Identity startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * 
   * @return startDate
   **/
  @JsonProperty("startDate")
  @ApiModelProperty(value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public Identity changePassword(Boolean changePassword) {
    this.changePassword = changePassword;
    return this;
  }

  /**
   * 
   * @return changePassword
   **/
  @JsonProperty("changePassword")
  @ApiModelProperty(value = "")
  public Boolean isChangePassword() {
    return changePassword;
  }

  public void setChangePassword(Boolean changePassword) {
    this.changePassword = changePassword;
  }

  public Identity cargo(String cargo) {
    this.cargo = cargo;
    return this;
  }

  /**
   * 
   * @return cargo
   **/
  @JsonProperty("cargo")
  @ApiModelProperty(value = "")
  public String getCargo() {
    return cargo;
  }

  public void setCargo(String cargo) {
    this.cargo = cargo;
  }

  public Identity institucion(String institucion) {
    this.institucion = institucion;
    return this;
  }

  /**
   * 
   * @return institucion
   **/
  @JsonProperty("institucion")
  @ApiModelProperty(value = "")
  public String getInstitucion() {
    return institucion;
  }

  public void setInstitucion(String institucion) {
    this.institucion = institucion;
  }

  public Identity dependencia(String dependencia) {
    this.dependencia = dependencia;
    return this;
  }

  /**
   * 
   * @return dependencia
   **/
  @JsonProperty("dependencia")
  @ApiModelProperty(value = "")
  public String getDependencia() {
    return dependencia;
  }

  public void setDependencia(String dependencia) {
    this.dependencia = dependencia;
  }

  public Identity nivel1(String nivel1) {
    this.nivel1 = nivel1;
    return this;
  }

  /**
   * 
   * @return nivel1
   **/
  @JsonProperty("nivel1")
  @ApiModelProperty(value = "")
  public String getNivel1() {
    return nivel1;
  }

  public void setNivel1(String nivel1) {
    this.nivel1 = nivel1;
  }

  public Identity nivel2(String nivel2) {
    this.nivel2 = nivel2;
    return this;
  }

  /**
   * 
   * @return nivel2
   **/
  @JsonProperty("nivel2")
  @ApiModelProperty(value = "")
  public String getNivel2() {
    return nivel2;
  }

  public void setNivel2(String nivel2) {
    this.nivel2 = nivel2;
  }

  public Identity nivel3(String nivel3) {
    this.nivel3 = nivel3;
    return this;
  }

  /**
   * 
   * @return nivel3
   **/
  @JsonProperty("nivel3")
  @ApiModelProperty(value = "")
  public String getNivel3() {
    return nivel3;
  }

  public void setNivel3(String nivel3) {
    this.nivel3 = nivel3;
  }

  public Identity nivel4(String nivel4) {
    this.nivel4 = nivel4;
    return this;
  }

  /**
   * 
   * @return nivel4
   **/
  @JsonProperty("nivel4")
  @ApiModelProperty(value = "")
  public String getNivel4() {
    return nivel4;
  }

  public void setNivel4(String nivel4) {
    this.nivel4 = nivel4;
  }

  public Identity correoAlternativo(String correoAlternativo) {
    this.correoAlternativo = correoAlternativo;
    return this;
  }

  /**
   * 
   * @return correoAlternativo
   **/
  @JsonProperty("correoAlternativo")
  @ApiModelProperty(value = "")
  public String getCorreoAlternativo() {
    return correoAlternativo;
  }

  public void setCorreoAlternativo(String correoAlternativo) {
    this.correoAlternativo = correoAlternativo;
  }

  public Identity nit(String nit) {
    this.nit = nit;
    return this;
  }
  
  public Identity dui(String dui) {
    this.dui = dui;
    return this;
  }

  /**
   * 
   * @return nit
   **/
  @JsonProperty("nit")
  @ApiModelProperty(value = "")
  public String getNit() {
    return nit;
  }

  public void setNit(String nit) {
    this.nit = nit;
  }
  
  /**
   * 
   * @return dui
   **/
  @JsonProperty("dui")
  @ApiModelProperty(value = "")
  public String getDui() {
    return dui;
  }

  public void setDui(String dui) {
    this.dui = dui;
  }

  public Identity extension(String extension) {
    this.extension = extension;
    return this;
  }

  /**
   * 
   * @return extension
   **/
  @JsonProperty("extension")
  @ApiModelProperty(value = "")
  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  public Identity tipoUsuario(String tipoUsuario) {
    this.tipoUsuario = tipoUsuario;
    return this;
  }

  /**
   * 
   * @return tipoUsuario
   **/
  @JsonProperty("tipoUsuario")
  @ApiModelProperty(value = "")
  public String getTipoUsuario() {
    return tipoUsuario;
  }

  public void setTipoUsuario(String tipoUsuario) {
    this.tipoUsuario = tipoUsuario;
  }

  public Identity comentarios(String comentarios) {
    this.comentarios = comentarios;
    return this;
  }

  /**
   * 
   * @return comentarios
   **/
  @JsonProperty("comentarios")
  @ApiModelProperty(value = "")
  public String getComentarios() {
    return comentarios;
  }

  public void setComentarios(String comentarios) {
    this.comentarios = comentarios;
  }

  public Identity creadoPor(String creadoPor) {
    this.creadoPor = creadoPor;
    return this;
  }

  /**
   * 
   * @return creadoPor
   **/
  @JsonProperty("creadoPor")
  @ApiModelProperty(value = "")
  public String getCreadoPor() {
    return creadoPor;
  }

  public void setCreadoPor(String creadoPor) {
    this.creadoPor = creadoPor;
  }

  public Identity actualizadoPor(String actualizadoPor) {
    this.actualizadoPor = actualizadoPor;
    return this;
  }

  /**
   * 
   * @return actualizadoPor
   **/
  @JsonProperty("actualizadoPor")
  @ApiModelProperty(value = "")
  public String getActualizadoPor() {
    return actualizadoPor;
  }

  public void setActualizadoPor(String actualizadoPor) {
    this.actualizadoPor = actualizadoPor;
  }

  public Identity creadoEn(String creadoEn) {
    this.creadoEn = creadoEn;
    return this;
  }

  /**
   * 
   * @return creadoEn
   **/
  @JsonProperty("creadoEn")
  @ApiModelProperty(value = "")
  public String getCreadoEn() {
    return creadoEn;
  }

  public void setCreadoEn(String creadoEn) {
    this.creadoEn = creadoEn;
  }

  public Identity actualizadoEn(String actualizadoEn) {
    this.actualizadoEn = actualizadoEn;
    return this;
  }

  /**
   * 
   * @return actualizadoEn
   **/
  @JsonProperty("actualizadoEn")
  @ApiModelProperty(value = "")
  public String getActualizadoEn() {
    return actualizadoEn;
  }

  public void setActualizadoEn(String actualizadoEn) {
    this.actualizadoEn = actualizadoEn;
  }

  public Identity justification(String justification) {
    this.justification = justification;
    return this;
  }

  /**
   * 
   * @return justification
   **/
  @JsonProperty("justification")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getJustification() {
    return justification;
  }

  public void setJustification(String justification) {
    this.justification = justification;
  }

  public Identity estado(String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * 
   * @return estado
   **/
  @JsonProperty("estado")
  @ApiModelProperty(value = "")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public Identity id(String id) {
    this.id = id;
    return this;
  }

  /**
   * 
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Identity password(String password) {
    this.password = password;
    return this;
  }

  /**
   * Password
   * @return password
   **/
  @JsonProperty("password")
  @ApiModelProperty(value = "Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Identity identity = (Identity) o;
    return Objects.equals(this.userLogin, identity.userLogin) &&
        Objects.equals(this.email, identity.email) &&
        Objects.equals(this.firstName, identity.firstName) &&
        Objects.equals(this.lastName, identity.lastName) &&
        Objects.equals(this.commonName, identity.commonName) &&
        Objects.equals(this.homePhone, identity.homePhone) &&
        Objects.equals(this.organizationName, identity.organizationName) &&
        Objects.equals(this.mobile, identity.mobile) &&
        Objects.equals(this.startDate, identity.startDate) &&
        Objects.equals(this.changePassword, identity.changePassword) &&
        Objects.equals(this.cargo, identity.cargo) &&
        Objects.equals(this.institucion, identity.institucion) &&
        Objects.equals(this.dependencia, identity.dependencia) &&
        Objects.equals(this.nivel1, identity.nivel1) &&
        Objects.equals(this.nivel2, identity.nivel2) &&
        Objects.equals(this.nivel3, identity.nivel3) &&
        Objects.equals(this.nivel4, identity.nivel4) &&
        Objects.equals(this.correoAlternativo, identity.correoAlternativo) &&
        Objects.equals(this.nit, identity.nit) &&
        Objects.equals(this.dui, identity.dui) &&
        Objects.equals(this.extension, identity.extension) &&
        Objects.equals(this.tipoUsuario, identity.tipoUsuario) &&
        Objects.equals(this.comentarios, identity.comentarios) &&
        Objects.equals(this.creadoPor, identity.creadoPor) &&
        Objects.equals(this.actualizadoPor, identity.actualizadoPor) &&
        Objects.equals(this.creadoEn, identity.creadoEn) &&
        Objects.equals(this.actualizadoEn, identity.actualizadoEn) &&
        Objects.equals(this.justification, identity.justification) &&
        Objects.equals(this.estado, identity.estado) &&
        Objects.equals(this.id, identity.id) &&
        Objects.equals(this.password, identity.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userLogin, email, firstName, lastName, commonName, homePhone, organizationName, mobile, startDate, changePassword, cargo, institucion, dependencia, nivel1, nivel2, nivel3, nivel4, correoAlternativo, nit, dui, extension, tipoUsuario, comentarios, creadoPor, actualizadoPor, creadoEn, actualizadoEn, justification, estado, id, password);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Identity {\n");
    
    sb.append("    userLogin: ").append(toIndentedString(userLogin)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    commonName: ").append(toIndentedString(commonName)).append("\n");
    sb.append("    homePhone: ").append(toIndentedString(homePhone)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    changePassword: ").append(toIndentedString(changePassword)).append("\n");
    sb.append("    cargo: ").append(toIndentedString(cargo)).append("\n");
    sb.append("    institucion: ").append(toIndentedString(institucion)).append("\n");
    sb.append("    dependencia: ").append(toIndentedString(dependencia)).append("\n");
    sb.append("    nivel1: ").append(toIndentedString(nivel1)).append("\n");
    sb.append("    nivel2: ").append(toIndentedString(nivel2)).append("\n");
    sb.append("    nivel3: ").append(toIndentedString(nivel3)).append("\n");
    sb.append("    nivel4: ").append(toIndentedString(nivel4)).append("\n");
    sb.append("    correoAlternativo: ").append(toIndentedString(correoAlternativo)).append("\n");
    sb.append("    nit: ").append(toIndentedString(nit)).append("\n");
    sb.append("    dui: ").append(toIndentedString(dui)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    tipoUsuario: ").append(toIndentedString(tipoUsuario)).append("\n");
    sb.append("    comentarios: ").append(toIndentedString(comentarios)).append("\n");
    sb.append("    creadoPor: ").append(toIndentedString(creadoPor)).append("\n");
    sb.append("    actualizadoPor: ").append(toIndentedString(actualizadoPor)).append("\n");
    sb.append("    creadoEn: ").append(toIndentedString(creadoEn)).append("\n");
    sb.append("    actualizadoEn: ").append(toIndentedString(actualizadoEn)).append("\n");
    sb.append("    justification: ").append(toIndentedString(justification)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
  
  
}

