/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Resource
 */
@ApiModel(description = "Resource")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class Resource   {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("subtype")
  private String subtype = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("table")
  private String table = null;

  @JsonProperty("userLoginTable")
  private String userLoginTable = null;

  @JsonProperty("parameters")
  private List<ResourceParameter> parameters = null;

  @JsonProperty("childTables")
  private List<ResourceChildTable> childTables = new ArrayList<ResourceChildTable>();

  public Resource id(String id) {
    this.id = id;
    return this;
  }

  /**
   * id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Resource type(String type) {
    this.type = type;
    return this;
  }

  /**
   * type
   * @return type
   **/
  @JsonProperty("type")
  @ApiModelProperty(value = "type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Resource subtype(String subtype) {
    this.subtype = subtype;
    return this;
  }

  /**
   * subtype
   * @return subtype
   **/
  @JsonProperty("subtype")
  @ApiModelProperty(value = "subtype")
  public String getSubtype() {
    return subtype;
  }

  public void setSubtype(String subtype) {
    this.subtype = subtype;
  }

  public Resource name(String name) {
    this.name = name;
    return this;
  }

  /**
   * name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Resource description(String description) {
    this.description = description;
    return this;
  }

  /**
   * description
   * @return description
   **/
  @JsonProperty("description")
  @ApiModelProperty(value = "description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Resource table(String table) {
    this.table = table;
    return this;
  }

  /**
   * table
   * @return table
   **/
  @JsonProperty("table")
  @ApiModelProperty(value = "table")
  public String getTable() {
    return table;
  }

  public void setTable(String table) {
    this.table = table;
  }

  public Resource userLoginTable(String userLoginTable) {
    this.userLoginTable = userLoginTable;
    return this;
  }

  /**
   * userLoginTable
   * @return userLoginTable
   **/
  @JsonProperty("userLoginTable")
  @ApiModelProperty(value = "userLoginTable")
  public String getUserLoginTable() {
    return userLoginTable;
  }

  public void setUserLoginTable(String userLoginTable) {
    this.userLoginTable = userLoginTable;
  }

  public Resource parameters(List<ResourceParameter> parameters) {
    this.parameters = parameters;
    return this;
  }

  public Resource addParametersItem(ResourceParameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<ResourceParameter>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

  /**
   * 
   * @return parameters
   **/
  @JsonProperty("parameters")
  @ApiModelProperty(value = "")
  @Valid
  public List<ResourceParameter> getParameters() {
    return parameters;
  }

  public void setParameters(List<ResourceParameter> parameters) {
    this.parameters = parameters;
  }

  public Resource childTables(List<ResourceChildTable> childTables) {
    this.childTables = childTables;
    return this;
  }

  public Resource addChildTablesItem(ResourceChildTable childTablesItem) {
    this.childTables.add(childTablesItem);
    return this;
  }

  /**
   * 
   * @return childTables
   **/
  @JsonProperty("childTables")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  @Valid
  public List<ResourceChildTable> getChildTables() {
    return childTables;
  }

  public void setChildTables(List<ResourceChildTable> childTables) {
    this.childTables = childTables;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Resource resource = (Resource) o;
    return Objects.equals(this.id, resource.id) &&
        Objects.equals(this.type, resource.type) &&
        Objects.equals(this.subtype, resource.subtype) &&
        Objects.equals(this.name, resource.name) &&
        Objects.equals(this.description, resource.description) &&
        Objects.equals(this.table, resource.table) &&
        Objects.equals(this.userLoginTable, resource.userLoginTable) &&
        Objects.equals(this.parameters, resource.parameters) &&
        Objects.equals(this.childTables, resource.childTables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, subtype, name, description, table, userLoginTable, parameters, childTables);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Resource {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    subtype: ").append(toIndentedString(subtype)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    table: ").append(toIndentedString(table)).append("\n");
    sb.append("    userLoginTable: ").append(toIndentedString(userLoginTable)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    childTables: ").append(toIndentedString(childTables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

