/*
 * OIM API Ministerio de Hacienda
 * Ministerio de Hacienda
 *
 * OpenAPI spec version: 1.0.0
 * Contact: oscar.delgado@mh.gob.sv
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package sv.gob.mh.oim.pojo;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-11-26T23:30:56.998Z")
public class Role   {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("privilege")
  private List<String> privilege = null;

  public Role name(String name) {
    this.name = name;
    return this;
  }

  /**
   * 
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Role privilege(List<String> privilege) {
    this.privilege = privilege;
    return this;
  }

  public Role addPrivilegeItem(String privilegeItem) {
    if (this.privilege == null) {
      this.privilege = new ArrayList<String>();
    }
    this.privilege.add(privilegeItem);
    return this;
  }

  /**
   * 
   * @return privilege
   **/
  @JsonProperty("privilege")
  @ApiModelProperty(value = "")
  public List<String> getPrivilege() {
    return privilege;
  }

  public void setPrivilege(List<String> privilege) {
    this.privilege = privilege;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Role role = (Role) o;
    return Objects.equals(this.name, role.name) &&
        Objects.equals(this.privilege, role.privilege);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, privilege);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Role {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    privilege: ").append(toIndentedString(privilege)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

